version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:80" # Expose backend on host port 8000
    env_file:
      - ./backend/.env  # ✅ Load backend env variables
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend_ng
      dockerfile: Dockerfile.local # A Dockerfile tailored for dev
      args:
        ENVIRONMENT: development  # 👈 Add this line
    container_name: angular_frontend
    ports:
      - "4200:8080" # Expose frontend on host port 4200
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
